apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor
  namespace: gulzat-project-hamster
rules:
- apiGroups: [""] 
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get", "update", "delete", "jlist", "watch"]



  