apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor
  namespace: gulzat-project-hamster
subjects:
- kind: ServiceAccount
  name: processor
roleRef:
  kind: Role
  name: processor
  apiGroup: rbac.authorization.k8s.io